name: Flutter Build

on:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.0'
        channel: 'stable'
    - run: flutter --version
    - run: flutter pub get
      working-directory: ./appui
    - run: flutter test
      working-directory: ./appui
    - run: flutter build web
      working-directory: ./appui
